CREATE DATABASE  IF NOT EXISTS 'PASARELAPAGO';
USE 'PASARELAPAGO';

DROP TABLE IF EXISTS 'USUARIO';

CREATE TABLE 'USUARIO'(
	'id_usuario' int(11) NOT NULL AUTO_INCREMENT,
	'nombre' varchar(50) DEFAULT NULL,
	'codigo' varchar(10) DEFAULT NULL,
	'correo' varchar(50) DEFAULT NULL,
	'escuela' varchar(30) DEFAULT NULL,
	PRIMARY KEY ('id_usuario')
)ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;